name: Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @playwright/test typescript ts-node @types/node dotenv

      - name: Install browsers
        run: npx playwright install

      - name: Set TS_NODE_PROJECT variable
        run: export TS_NODE_PROJECT=./tsconfig.json

      - name: Run Playwright tests
        run: npx playwright test